# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0002_auto_20170425_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
