# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0003_auto_20170425_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
    ]
