# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0004_remove_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images'),
        ),
    ]
