# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0005_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images'),
        ),
    ]
