# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0006_auto_20170507_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
