# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0007_resource_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='resource',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
