# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0008_auto_20170508_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='value',
            field=models.TextField(max_length=8000),
        ),
    ]
