# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0011_auto_20170522_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
