# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0013_auto_20170523_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='resource',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
