# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0014_auto_20170523_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_liked_by_user',
            field=models.IntegerField(default=0),
        ),
    ]
