# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0015_auto_20170523_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
