# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0018_auto_20170523_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
