# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avacatapp', '0020_auto_20170608_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_viewed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
